import Foundation
@testable import domain

extension Individual {
  static func stub(index: Int = 0,
                   loc: Coord = .init(x: 0, y: 0),
                   genome: Genome = makeRandomGenome(10...10),
                   probeDistance: (short: Int, long: Int) = (short: 3, long: 16),
                   responsiveness: Double = 0.5,
                   maxNumberOfNeurons: Int = 10,
                   actions: Int = 17, sensors: Int = 20) -> Self {
    .init(index: index,
          loc: loc,
          genome: genome,
          probeDistance: probeDistance,
          responsiveness: responsiveness,
          maxNumberOfNeurons: maxNumberOfNeurons,
          actions: actions,
          sensors: sensors)
  }
}

extension Parameters {
  static func stub(population: Int = Parameters.defaults.population,
                   stepsPerGeneration: Int = Parameters.defaults.stepsPerGeneration,
                   maxGenerations: Int = Parameters.defaults.maxGenerations,
                   signalLayers: Int = Parameters.defaults.signalLayers,
                   genomeMaxLength: Int = Parameters.defaults.genomeMaxLength,
                   maxNumberNeurons: Int = Parameters.defaults.maxNumberNeurons,
                   pointMutationRate: Double = Parameters.defaults.pointMutationRate,
                   geneInsertionDeletionRate: Double = Parameters.defaults.geneInsertionDeletionRate,
                   deletionRatio: Double = Parameters.defaults.deletionRatio,
                   sexualReproduction: Bool = Parameters.defaults.sexualReproduction,
                   chooseParentsByFitness: Bool = Parameters.defaults.chooseParentsByFitness,
                   populationSensorRadius: Double = Parameters.defaults.populationSensorRadius,
                   signalSensorRadius: Int = Parameters.defaults.signalSensorRadius,
                   responsiveness: (value: Double, kFactor: Int) = Parameters.defaults.responsiveness,
                   initialResponsiveness: Double = Parameters.defaults.initialResponsiveness,
                   probeDistance: (short: Int, long: Int) = Parameters.defaults.probeDistance,
                   genomeComparisonMethod: GenomeComparison = Parameters.defaults.genomeComparisonMethod,
                   challenge: Challenge? = Parameters.defaults.challenge,
                   generatedBarrier: GeneratedBarrier? = Parameters.defaults.generatedBarrier,
                   shouldPersistManualBarriers: Bool = Parameters.defaults.shouldPersistManualBarriers,
                   replaceBarrier: (GeneratedBarrier, Int)? = Parameters.defaults.replaceBarrier,
                   size: Size = Parameters.defaults.size,
                   genomeInitialLength: ClosedRange<Int> = Parameters.defaults.genomeInitialLength,
                   sensors: [Sensor] = Parameters.defaults.sensors,
                   actions: [Action] = Parameters.defaults.actions) -> Self {
    .init(population: population,
          stepsPerGeneration: stepsPerGeneration,
          maxGenerations: maxGenerations,
          signalLayers: signalLayers,
          genomeMaxLength: genomeMaxLength,
          maxNumberNeurons: maxNumberNeurons,
          pointMutationRate: pointMutationRate,
          geneInsertionDeletionRate: geneInsertionDeletionRate,
          deletionRatio: deletionRatio,
          sexualReproduction: sexualReproduction,
          chooseParentsByFitness: chooseParentsByFitness,
          populationSensorRadius: populationSensorRadius,
          signalSensorRadius: signalSensorRadius,
          responsiveness: responsiveness,
          initialResponsiveness: initialResponsiveness,
          probeDistance: probeDistance,
          genomeComparisonMethod: genomeComparisonMethod,
          challenge: challenge,
          generatedBarrier: generatedBarrier,
          shouldPersistManualBarriers: shouldPersistManualBarriers,
          replaceBarrier: replaceBarrier,
          size: size,
          genomeInitialLength: genomeInitialLength,
          sensors: sensors,
          actions: actions)
  }
}
